---
- hosts: all
  become: true
  become_method: enable  
  tasks:
    - name: Update and upgrade packages 
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
        autoremove: yes
